version: '4.18.0'

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=fsdb
    ports:
      - 3307:3306
    networks:
      - backend
    volumes:
      - mysql-db:/var/lib/mysql

  server:
    container_name: server-circleup
    restart: unless-stopped
    image: server-circleup:1
    build: ./server
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=mysql
      - DB_NAME=fsdb
    ports:
      - 4001:4001
    networks:
      - backend
      - frontend
    depends_on:
      - mysql

  client:
    container_name: client-circleup
    restart: unless-stopped
    image: client:1
    build: ./client
    ports:
      - 3000:3000
    networks:
      - frontend
    depends_on:
      - server
networks:
  backend:
  frontend:
volumes:
  mysql-db: